# permissions for end users to view scopetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scopetemplate-viewer-role
rules:
- apiGroups:
  - operators.io.operator-framework
  resources:
  - scopetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.io.operator-framework
  resources:
  - scopetemplates/status
  verbs:
  - get
