name: e2e
on:
  pull_request: {}
  push: {}

jobs:
  unit:
    name: e2e
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run e2e tests
      run: make test-e2e

