name: oria-operator ci

on:
  pull_request: {}
  workflow_dispatch:

jobs:
  go-apidiff:
    name: go-apidiff
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      id: go
    - name: Print out Go env
      run: go env
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run go-apidiff
      uses: joelanford/go-apidiff@main