name: unit
on:
  pull_request: {}
  push: {}

jobs:
  unit:
    name: unit
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Run unit tests
      run: make test
    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: cover.out

